// <auto-generated />
using ArticalProject.Data.DataEf;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArticalProject.Data.Migrations
{
    [DbContext(typeof(DataContextEf))]
    [Migration("20250126125202_DbCategory")]
    partial class DbCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticalProject.Core.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("ArticalProject.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "تطوير الويب"
                        },
                        new
                        {
                            Id = 2,
                            Name = "تطبيقات الموبايل"
                        },
                        new
                        {
                            Id = 3,
                            Name = "الذكاء الاصطناعي"
                        },
                        new
                        {
                            Id = 4,
                            Name = "أمن المعلومات"
                        },
                        new
                        {
                            Id = 5,
                            Name = "برمجة"
                        },
                        new
                        {
                            Id = 6,
                            Name = "الحوسبة السحابية"
                        },
                        new
                        {
                            Id = 7,
                            Name = "قواعد البيانات"
                        },
                        new
                        {
                            Id = 8,
                            Name = "تجربة المستخدم"
                        },
                        new
                        {
                            Id = 9,
                            Name = "تطوير الألعاب"
                        },
                        new
                        {
                            Id = 10,
                            Name = "تقنيات حديثة"
                        },
                        new
                        {
                            Id = 11,
                            Name = "إنترنت الأشياء"
                        },
                        new
                        {
                            Id = 12,
                            Name = "تعلم الآلة"
                        },
                        new
                        {
                            Id = 13,
                            Name = "تحليل البيانات"
                        },
                        new
                        {
                            Id = 14,
                            Name = "أنظمة التشغيل"
                        },
                        new
                        {
                            Id = 15,
                            Name = "شبكات الحاسوب"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
